  File "C:\Dropbox\GitHub\HimalCo\dev\lib\lmf\user\na\alexis/../../../..\lmf\src\input\mdf.py", line 117, in mdf_read
    Warning: MDF marker 'xf' encountered for lexeme 'æ˩mo˧' is not defined in configuration
  File "./src\utils\attr.py", line 35, in check_attr_range
    Warning: Part of speech value 'conj' encountered for lexeme 'lɑ˧ɬɑ˧˥' is not allowed
  File "./src\utils\attr.py", line 35, in check_attr_range
    Warning: Part of speech value 'conj' encountered for lexeme 'le˧-tɑ˧˥' is not allowed
  File "./src\utils\attr.py", line 35, in check_attr_range
    Warning: Part of speech value 'conj' encountered for lexeme '‑bi' is not allowed
  File "C:\Dropbox\GitHub\HimalCo\dev\lib\lmf\user\na\alexis/../../../..\lmf\src\input\mdf.py", line 117, in mdf_read
    Warning: MDF marker 'rf' encountered for lexeme '‑bi˩' is not defined in configuration
  File "C:\Dropbox\GitHub\HimalCo\dev\lib\lmf\user\na\alexis/../../../..\lmf\src\input\mdf.py", line 117, in mdf_read
    Warning: MDF marker 'rf' encountered for lexeme '‑bi˩' is not defined in configuration
  File "./src\utils\attr.py", line 35, in check_attr_range
    Warning: Part of speech value 'conj' encountered for lexeme '‑lɑ' is not allowed
  File "./src\utils\attr.py", line 35, in check_attr_range
    Warning: Part of speech value 'conj' encountered for lexeme '‑ɳɯ' is not allowed
  File "./src\utils\attr.py", line 35, in check_attr_range
    Warning: Part of speech value 'conj' encountered for lexeme '‑pɤ˧to˩' is not allowed
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'dzi˩si˩' does not exist. Please solve this issue by checking the related form of lexical entry 'dzi˧dzi˧'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'dʑɯ˧njɤ˧, dʑɯ˧ʈʂʰwæ#˥' does not exist. Please solve this issue by checking the related form of lexical entry 'dʑɯ˧ɭɯ˧'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'dʑɯ˩nɑ˩mi˩-ʁo˩, dʑɯ˩ʁo˩' does not exist. Please solve this issue by checking the related form of lexical entry 'dʑɯ˩nɑ˩mi˩'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'dʑɯ˩nɑ˩mi˩, dʑɯ˩ʁo˩' does not exist. Please solve this issue by checking the related form of lexical entry 'dʑɯ˩nɑ˩mi˩-ʁo˩'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'dʑɯ˧ɭɯ˧, dʑɯ˧ʈʂʰwæ#˥' does not exist. Please solve this issue by checking the related form of lexical entry 'dʑɯ˧njɤ˧'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'dʑɯ˩pɤ˩qʰv˩, dʑɯ˩pɤ˩tv˩qʰv˥' does not exist. Please solve this issue by checking the related form of lexical entry 'dʑɯ˩pɤ˩-kv˧hĩ˩'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'dʑɯ˩pɤ˩-kv˧hĩ˩, dʑɯ˩pɤ˩tv˩qʰv˥' does not exist. Please solve this issue by checking the related form of lexical entry 'dʑɯ˩pɤ˩qʰv˩'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'dʑɯ˩pɤ˩qʰv˩, dʑɯ˩pɤ˩-kv˧hĩ˩' does not exist. Please solve this issue by checking the related form of lexical entry 'dʑɯ˩pɤ˩tv˩qʰv˥'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'dʑɯ˩nɑ˩mi˩, dʑɯ˩nɑ˩mi˩-ʁo˩' does not exist. Please solve this issue by checking the related form of lexical entry 'dʑɯ˩ʁo˩'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'dʑɯ˧ɭɯ˧, dʑɯ˧njɤ˧' does not exist. Please solve this issue by checking the related form of lexical entry 'dʑɯ˧ʈʂʰwæ#˥'.
  File "./src\core\lexicon.py", line 323, in check_cross_references
    Warning: Several lexical entries 'ɖʐv˥' exist. Please solve this issue by renaming lexical entries correctly or by precising the homonym number.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'ə˧ze˧, ə˧-dzɤ˧~dzɤ˥' does not exist. Please solve this issue by checking the related form of lexical entry 'ə˧-dzɤ˥$'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'gɤ˩-' does not exist. Please solve this issue by checking the related form of lexical entry 'gɤ˩dzɤ˧'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'gɤ˩-, gɤ˩-ʈʂʰɯ˧qo˧, gɤ˩-tʰv˧qo˧,' does not exist. Please solve this issue by checking the related form of lexical entry 'gɤ˩-qo˧'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'gɤ˩-, gɤ˩-qo˧, gɤ˩-tʰv˧qo˧, gɤ˩-ʈʂʰɯ˧qo˧' does not exist. Please solve this issue by checking the related form of lexical entry 'gɤ˩-ʈʂʰɯ˧-gi#˥'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'gɤ˩-, gɤ˩-qo˧, gɤ˩-tʰv˧qo˧' does not exist. Please solve this issue by checking the related form of lexical entry 'gɤ˩-ʈʂʰɯ˧qo˧'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'gɤ˩‑, gɤ˩-qo˧, gɤ˩-tʰv˧qo˧, gɤ˩-ʈʂʰɯ˧qo˧' does not exist. Please solve this issue by checking the related form of lexical entry 'gɤ˩-tʰv˧-gi#˥'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'gɤ˩‑, gɤ˩-qo˧, gɤ˩-ʈʂʰɯ˧qo˧' does not exist. Please solve this issue by checking the related form of lexical entry 'gɤ˩-tʰv˧qo˧'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'gɤ˩-qo˧, gɤ˩-tʰv˧qo˧, gɤ˩-ʈʂʰɯ˧qo˧' does not exist. Please solve this issue by checking the related form of lexical entry 'gɤ˩‑'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'kɤ˩kɤ˧˥' does not exist. Please solve this issue by checking the related form of lexical entry 'kɤ˧˥'.
  File "./src\core\lexicon.py", line 323, in check_cross_references
    Warning: Several lexical entries 'lɑ˧˥' exist. Please solve this issue by renaming lexical entries correctly or by precising the homonym number.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'lo˧; ʝi˥' does not exist. Please solve this issue by checking the related form of lexical entry 'lo˧ʝi˧'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'ɳæ˩=ɻæ˧, no˧=ɻ˩' does not exist. Please solve this issue by checking the related form of lexical entry 'ɳæ˧=ɻ˩'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'ɳæ˧=ɻ˩, no˧=ɻ˩' does not exist. Please solve this issue by checking the related form of lexical entry 'ɳæ˩=ɻæ˧'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'njɤ˧kv˩, tsʰɤ˧˥a' does not exist. Please solve this issue by checking the related form of lexical entry 'njɤ˧kv˩-njɤ˩tsʰɤ˩'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'pɤ˩tɕɯ˧-ʁo˧ɖɯ˧˥, pɤ˩tɕɯ˧-pɤ˥mi˩' does not exist. Please solve this issue by checking the related form of lexical entry 'pɤ˩tɕɯ˧˥'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'pɤ˩tɕɯ˧˥, pɤ˩tɕɯ˧-ʁo˧ɖɯ˧˥' does not exist. Please solve this issue by checking the related form of lexical entry 'pɤ˩tɕɯ˧-pɤ˥mi˩'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'pɤ˩tɕɯ˧˥, pɤ˩tɕɯ˧-pɤ˥mi˩' does not exist. Please solve this issue by checking the related form of lexical entry 'pɤ˩tɕɯ˧-ʁo˧ɖɯ˧˥'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'pʰv˧2; ʐo˩a' does not exist. Please solve this issue by checking the related form of lexical entry 'pʰv˧ʐo˧˥'.
  File "./src\core\lexicon.py", line 323, in check_cross_references
    Warning: Several lexical entries 'ʈʂe˥' exist. Please solve this issue by renaming lexical entries correctly or by precising the homonym number.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'si˧kʰɯ˧ɭɯ˧bv˥' does not exist. Please solve this issue by checking the related form of lexical entry 'si˧kʰɯ#˥'.
  File "./src\core\lexicon.py", line 323, in check_cross_references
    Warning: Several lexical entries 'sɑ˥' exist. Please solve this issue by renaming lexical entries correctly or by precising the homonym number.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry '-ni˧gv˧˥' does not exist. Please solve this issue by checking the related form of lexical entry 'tʰɑ˧-ni˥-ni˩-gv˩'.
  File "./src\core\lexicon.py", line 314, in check_cross_references
    Warning: Lexical entry 'tɕʰɯ˩˥, di˧˥' does not exist. Please solve this issue by checking the related form of lexical entry 'tɕʰɯ˩di˩'.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'bi˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ɖæ˩a' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ɖwæ˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ɖʐo˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ɖʐv˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ɖʐv˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'gi˩' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'gv˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'hṽ˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'hwɤ˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'jɤ˩po˧' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ʝi˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ʝi˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ʝi˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'kɯ˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'kʰv˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'kʰv˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'pɤ˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'pʰv˩a' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ɻ̃˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ʁo˧dzi˩-di˩' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ʁo˩b' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ʁwɤ˧a' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'sɑ˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ʂo˧' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ʂɯ˩tsɯ˧' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ʂwæ˧' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'tɑ˧pi˧' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'tʰo˥a' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'tsʰe˩b' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ʈʂe˥' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ʈʂwɤ˧a' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'ze˩' exist. Please solve this issue by precising the homonym number.
  File "./src\core\lexicon.py", line 195, in compare
    Warning: Several lexical entries 'zo˧tʰi˧' exist. Please solve this issue by precising the homonym number.
